<template>
  <component
    :is="resolvedIcon"
    v-if="resolvedIcon"
    :size="numericSize"
    :stroke-width="strokeWidth"
    :color="color"
    :fill="computedFill"
    class="app-icon"
    :class="customClass"
    aria-hidden="true"
    v-bind="$attrs"
  />
</template>

<script setup>
import { computed } from 'vue'
import {
  Compass,
  Calendar,
  Luggage,
  LayoutDashboard,
  Sun,
  Moon,
  LogIn,
  LogOut,
  User,
  Users,
  Search,
  X,
  Check,
  CheckCircle2,
  AlertTriangle,
  AlertCircle,
  Info,
  Heart,
  Star,
  MapPin,
  Map,
  Navigation,
  Route,
  Plane,
  PlaneTakeoff,
  PlaneLanding,
  Car,
  Bus,
  Train,
  Bike,
  Footprints,
  Volume2,
  VolumeX,
  Leaf,
  Sparkles,
  Bot,
  Hotel,
  Bed,
  Maximize2,
  Utensils,
  Coffee,
  Landmark,
  Share2,
  Download,
  Printer,
  Trash2,
  Pencil,
  Edit3,
  Bookmark,
  Save,
  RefreshCw,
  Sliders,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  TrendingUp,
  Wallet,
  Coins,
  Crown,
  Gem,
  Trophy,
  Award,
  Lock,
  Unlock,
  Copy,
  Tag,
  Dices,
  Shield,
  Bell,
  Settings,
  Cpu,
  BarChart2,
  Globe,
  CloudRain,
  CloudSun,
  Cloud,
  CloudLightning,
  Snowflake,
  Wind,
  Phone,
  Clock,
  Ticket,
  Camera,
  Layers,
  HelpCircle,
  FileText,
  FileCheck,
  ExternalLink,
  Flame,
  Sunrise,
  Sunset,
  ArrowRight,
  ArrowDown,
  Shuffle,
  Send,
  MessageSquare,
  Plus,
  Rocket,
  Smartphone,
  BookOpen,
  Sprout
} from '@lucide/vue'

const props = defineProps({
  name: {
    type: String,
    required: true
  },
  size: {
    type: [Number, String],
    default: 18
  },
  strokeWidth: {
    type: [Number, String],
    default: 2
  },
  color: {
    type: String,
    default: 'currentColor'
  },
  fill: {
    type: String,
    default: 'none'
  },
  filled: {
    type: Boolean,
    default: false
  },
  customClass: {
    type: String,
    default: ''
  }
})

const numericSize = computed(() => {
  const n = Number(props.size)
  return isNaN(n) ? 18 : n
})

const iconRegistry = {
  // Direct names (PascalCase & lowercase/kebab-case)
  compass: Compass,
  calendar: Calendar,
  luggage: Luggage,
  briefcase: Luggage,
  dashboard: LayoutDashboard,
  layoutdashboard: LayoutDashboard,
  grid: LayoutDashboard,
  admin: LayoutDashboard,
  sun: Sun,
  moon: Moon,
  login: LogIn,
  signin: LogIn,
  logout: LogOut,
  user: User,
  users: Users,
  people: Users,
  search: Search,
  x: X,
  close: X,
  clear: X,
  check: Check,
  checkcircle: CheckCircle2,
  checkcircle2: CheckCircle2,
  alert: AlertTriangle,
  warning: AlertTriangle,
  alerttriangle: AlertTriangle,
  alertcircle: AlertCircle,
  info: Info,
  help: HelpCircle,
  heart: Heart,
  star: Star,
  pin: MapPin,
  mappin: MapPin,
  location: MapPin,
  map: Map,
  navigation: Navigation,
  direction: Navigation,
  route: Route,
  plane: Plane,
  flight: Plane,
  planing: Plane,
  planetakeoff: PlaneTakeoff,
  planelanding: PlaneLanding,
  car: Car,
  bus: Bus,
  train: Train,
  bike: Bike,
  motorbike: Bike,
  bicycle: Bike,
  walk: Footprints,
  walking: Footprints,
  footprints: Footprints,
  transit: Car,
  volume: Volume2,
  volume2: Volume2,
  volumex: VolumeX,
  mute: VolumeX,
  unmute: Volume2,
  leaf: Leaf,
  eco: Leaf,
  esg: Leaf,
  nature: Leaf,
  sparkles: Sparkles,
  magic: Sparkles,
  ai: Sparkles,
  bot: Bot,
  robot: Bot,
  hotel: Hotel,
  bed: Bed,
  maximize: Maximize2,
  maximize2: Maximize2,
  building: Hotel,
  stay: Hotel,
  utensils: Utensils,
  food: Utensils,
  restaurant: Utensils,
  coffee: Coffee,
  cafe: Coffee,
  drink: Coffee,
  landmark: Landmark,
  attraction: Landmark,
  sight: Landmark,
  share: Share2,
  share2: Share2,
  download: Download,
  print: Printer,
  printer: Printer,
  trash: Trash2,
  trash2: Trash2,
  delete: Trash2,
  remove: Trash2,
  pencil: Pencil,
  edit: Edit3,
  edit3: Edit3,
  bookmark: Bookmark,
  save: Save,
  disk: Save,
  refresh: RefreshCw,
  refreshcw: RefreshCw,
  sync: RefreshCw,
  reload: RefreshCw,
  rotate: RefreshCw,
  shuffle: Shuffle,
  sliders: Sliders,
  filter: Sliders,
  chevrondown: ChevronDown,
  chevronup: ChevronUp,
  chevronleft: ChevronLeft,
  chevronright: ChevronRight,
  trendingup: TrendingUp,
  trend: TrendingUp,
  wallet: Wallet,
  coins: Coins,
  cash: Coins,
  money: Wallet,
  budget: Wallet,
  crown: Crown,
  vip: Crown,
  gem: Gem,
  diamond: Gem,
  luxury: Gem,
  trophy: Trophy,
  award: Award,
  medal: Award,
  lock: Lock,
  unlock: Unlock,
  copy: Copy,
  tag: Tag,
  dices: Dices,
  random: Dices,
  shield: Shield,
  security: Shield,
  bell: Bell,
  notify: Bell,
  notification: Bell,
  settings: Settings,
  config: Settings,
  gear: Settings,
  cpu: Cpu,
  barchart: BarChart2,
  barchart2: BarChart2,
  chart: BarChart2,
  stats: BarChart2,
  globe: Globe,
  crawler: Globe,
  web: Globe,
  cloudrain: CloudRain,
  rain: CloudRain,
  cloudsun: CloudSun,
  cloud: Cloud,
  cloudlightning: CloudLightning,
  thunder: CloudLightning,
  snowflake: Snowflake,
  snow: Snowflake,
  wind: Wind,
  phone: Phone,
  call: Phone,
  clock: Clock,
  time: Clock,
  ticket: Ticket,
  voucher: Ticket,
  pass: Ticket,
  camera: Camera,
  photo: Camera,
  layers: Layers,
  filetext: FileText,
  file: FileText,
  pdf: FileText,
  filecheck: FileCheck,
  externallink: ExternalLink,
  link: ExternalLink,
  flame: Flame,
  hot: Flame,
  fire: Flame,
  sunrise: Sunrise,
  sunset: Sunset,
  arrowright: ArrowRight,
  arrowdown: ArrowDown,
  down: ArrowDown,
  send: Send,
  messagesquare: MessageSquare,
  chat: MessageSquare,
  message: MessageSquare,
  plus: Plus,
  add: Plus,
  rocket: Rocket,
  smartphone: Smartphone,
  mobile: Smartphone,
  bookopen: BookOpen,
  book: BookOpen,
  sprout: Sprout,
  plant: Sprout,

  // Direct component mappings
  Compass,
  Calendar,
  Luggage,
  LayoutDashboard,
  Sun,
  Moon,
  LogIn,
  LogOut,
  User,
  Users,
  Search,
  X,
  Check,
  CheckCircle2,
  AlertTriangle,
  AlertCircle,
  Info,
  Heart,
  Star,
  MapPin,
  Map,
  Navigation,
  Route,
  Plane,
  PlaneTakeoff,
  PlaneLanding,
  Car,
  Bus,
  Train,
  Bike,
  Footprints,
  Volume2,
  VolumeX,
  Leaf,
  Sparkles,
  Bot,
  Hotel,
  Utensils,
  Coffee,
  Landmark,
  Share2,
  Download,
  Printer,
  Trash2,
  Pencil,
  Edit3,
  Bookmark,
  Save,
  RefreshCw,
  Sliders,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  TrendingUp,
  Wallet,
  Coins,
  Crown,
  Gem,
  Trophy,
  Award,
  Lock,
  Unlock,
  Copy,
  Tag,
  Dices,
  Shield,
  Bell,
  Settings,
  Cpu,
  BarChart2,
  Globe,
  CloudRain,
  CloudSun,
  Cloud,
  CloudLightning,
  Snowflake,
  Wind,
  Phone,
  Clock,
  Ticket,
  Camera,
  Layers,
  HelpCircle,
  FileText,
  FileCheck,
  ExternalLink,
  Flame,
  Sunrise,
  Sunset,
  ArrowRight,
  ArrowDown,
  Shuffle,

  // EMOJI MAPPINGS
  '⬇️': ArrowDown,
  '⬇': ArrowDown,
  '✕': X,
  '❌': X,
  '✓': Check,
  '✅': CheckCircle2,
  '★': Star,
  '⭐': Star,
  '♥': Heart,
  '♡': Heart,
  '❤': Heart,
  '❤️': Heart,
  '🤍': Heart,
  '🔇': VolumeX,
  '🔊': Volume2,
  '🌿': Leaf,
  '🍃': Leaf,
  '🏅': Award,
  '🏆': Trophy,
  '✨': Sparkles,
  '🍲': Utensils,
  '🍜': Utensils,
  '🍽': Utensils,
  '🥢': Utensils,
  '🌤': CloudSun,
  '🌤️': CloudSun,
  '☀️': Sun,
  '☀': Sun,
  '⛅': CloudSun,
  '🌧': CloudRain,
  '🌧️': CloudRain,
  '⛈': CloudLightning,
  '⛈️': CloudLightning,
  '☔': CloudRain,
  '❄': Snowflake,
  '🌫': Wind,
  '🏛': Landmark,
  '🏛️': Landmark,
  '🏰': Landmark,
  '🛕': Landmark,
  '⛩': Landmark,
  '🏨': Hotel,
  '🏡': Hotel,
  '🛖': Hotel,
  '☕': Coffee,
  '🔍': Search,
  '📍': MapPin,
  '📌': MapPin,
  '🗺': Map,
  '🗺️': Map,
  '🧭': Compass,
  '✈': Plane,
  '🛫': PlaneTakeoff,
  '🛬': PlaneLanding,
  '🔀': Shuffle,
  '🚩': MapPin,
  '🛣': Route,
  '🛣️': Route,
  '📅': Calendar,
  '👥': Users,
  '🎒': Luggage,
  '🧳': Luggage,
  '💎': Gem,
  '👑': Crown,
  '🚨': AlertTriangle,
  '⚠': AlertTriangle,
  '⚠️': AlertTriangle,
  '⛔': AlertCircle,
  '🚫': AlertCircle,
  '⚡': Sparkles,
  '💡': Sparkles,
  '🚌': Bus,
  '🚗': Car,
  '🚕': Car,
  '🚆': Train,
  '🚉': Train,
  '🏍': Bike,
  '🛵': Bike,
  '🚲': Bike,
  '🚶': Footprints,
  '🛡': Shield,
  '🛡️': Shield,
  '🤖': Bot,
  '🧠': Cpu,
  '🕒': Clock,
  '📞': Phone,
  '🎫': Ticket,
  '🎟': Ticket,
  '📸': Camera,
  '🎉': Sparkles,
  '🎯': Trophy,
  '💰': Wallet,
  '💸': Wallet,
  '💵': Wallet,
  '🔄': RefreshCw,
  '💾': Save,
  '📱': Phone,
  '📄': FileText,
  '📋': FileText,
  '📖': FileText,
  '🌅': Sunrise,
  '🌆': Sunset,
  '🌙': Moon,
  '🏷': Tag,
  '🔒': Lock,
  '🔗': ExternalLink,
  '🗑': Trash2,
  '✏': Pencil,
  '✏️': Pencil,
  '✍': Pencil,
  '🎲': Dices,
  '🔔': Bell,
  '⚙': Settings,
  '⚙️': Settings,
  '📊': BarChart2,
  '🌐': Globe,
  '🕷': Globe,
  '🕷️': Globe,
  '🌉': Landmark,
  '🌾': Leaf,
  '🌲': Leaf,
  '⛵': Compass,
  '🏖': Sun,
  '🏝': Sun,
  '🌴': Leaf,
  '🌊': Compass,
  '⛰': Landmark,
  '🏔': Landmark,
  '🌄': Sunrise,
  '🏞': Landmark,
  '🌳': Leaf,
  '🎋': Leaf,
  '🌸': Sparkles,
  '🌺': Sparkles,
  '🏙': Landmark,
  '🔥': Flame,
  '🏮': Sparkles,
  '🏜': Sun,
  '🌋': Landmark,
  '⚓': Compass
}

const resolvedIcon = computed(() => {
  if (!props.name) return null
  const trimmed = String(props.name).trim()

  // 1. Direct registry lookup (handles emojis and PascalCase)
  if (iconRegistry[trimmed]) {
    return iconRegistry[trimmed]
  }

  // 2. Lowercase / sanitized lookup
  const cleanKey = trimmed.toLowerCase().replace(/[^a-z0-9]/g, '')
  if (iconRegistry[cleanKey]) {
    return iconRegistry[cleanKey]
  }

  // 3. Fallback for star or heart special cases
  if (trimmed === '★' || trimmed === 'star') return Star
  if (trimmed === '♥' || trimmed === 'heart') return Heart
  if (trimmed === '♡') return Heart

  // 4. Default graceful fallback: Sparkles or Info if not found
  return Sparkles
})

const computedFill = computed(() => {
  if (props.filled) return props.color || 'currentColor'
  if (props.name === '♥' || props.name === '★' || props.name === 'heart-filled' || props.name === 'star-filled') {
    return props.color || 'currentColor'
  }
  return props.fill
})
</script>

<style scoped>
.app-icon {
  display: inline-block;
  vertical-align: -0.15em;
  flex-shrink: 0;
  transition: transform 0.2s cubic-bezier(0.16, 1, 0.3, 1), color 0.2s ease;
}
</style>
